language: python
python:
  - "2.7"
  - "pypy3.5"
cache: pip
install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - sudo pip install unidecode
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls